spring:
  flyway:
    enabled: false
    clean-disabled: false
  jpa:
    show-sql: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: jobee
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jobee}
    username: ${DATABASE_USER:abrizvi}
    password: ${DATABASE_PASSWORD:Password!}
  jwt:
    secret: ${JWT_SECRET:06d508be1f0e59cb5bfde3e8f5f3872c34f48dbf14df9f2cc3c5c510e4988246}
    # TODO: Change to proper expiration times
    accessTokenExpiration: 604800000 # 7 days in milliseconds
    refreshTokenExpiration: 2592000000 # 30 days in milliseconds
cloud:
  aws:
    region: ${AWS_REGION:us-west-2}
    bucket: ${AWS_S3_BUCKET:jobee-backend}
    accessKey: ${AWS_ACCESS_KEY_ID:your-access-key-id}
    secretKey: ${AWS_SECRET_ACCESS_KEY:your-secret-access-key}
twilio:
  accountSid: ${TWILIO_ACCOUNT_SID:your-twilio-account-sid}
  authToken: ${TWILIO_AUTH_TOKEN:your-twilio-auth-token}
  phoneNumber: ${TWILIO_PHONE_NUMBER:+16472705508}
email:
  from: ${JOBEE_EMAIL_FROM:no-reply@jobee.solutions}
openai:
  apiKey: ${OPENAI_API_KEY:your-openai-api-key}
zoom:
  clientId: ${ZOOM_CLIENT_ID:your-zoom-client-id}
  clientSecret: ${ZOOM_CLIENT_SECRET:your-zoom-client-secret}
resend:
  apiKey: ${RESEND_API_KEY:your-resend-api-key}
